douBao:
  accessKeyId: AKLTYjJjZTIxYzM2MGM2NDZhNmExYzQxNzEyMTQ2ZmU5OTQ
  secretAccessKey: T0RRNU1tVmxZbUkxWlRjd05HVTFNVGt3TURjNFpEbGxNRFF6WlRBNU1HWQ==
  apiKey: 3502ebc7-9dc8-4062-8529-9650b4989d60
  modelID: doubao-seed-2-0-code-preview-260215
  baseUrl: https://ark.cn-beijing.volces.com/api/v3
baiDu:
  baseUrl: https://qianfan.baidubce.com/v2/ai_search/web_search
  apiKey: bce-v3/ALTAK-hOfKGbMFkzBMeVh4nSbBy/1f0b33ef3b0437d8128a5779c6995471e4b32498
